### ISSUE TITLE
Idea to overcome cluster problem with ip's in kubernetes

### ISSUE THREAD

**Issue by jochen1234** [eclipse/amlen#111]
Hi @jonquark ,

today I had an idea to overcome the ip problem in kubernetes using the cluster functionality because of floating ip's within pods. What about adding a property to server.conf which say DISABLE_LOCAL_CLUSTER_IP_CHECK=true/false?

If false all things stays as they are.

If yes amlen only check if it can reach itself via the ip. The only things you have to have is a service like this for any instance of the stateful set. Which can be add by the operator I currently develop.

```
kind: Service
apiVersion: v1
metadata:
  name: psb-amlennew-0
  namespace: speed-platform-qa
  labels:
    app: psb
    deployment: psb-amlennew
    psb-commit: 7109e7a
    psb-config-commit: 2c55186
    release: feature-823-rework-deployments
    service: psb-amlennew-0
    statefulset: psb-amlennew
    template: amlen
spec:
  externalTrafficPolicy: Cluster
  loadBalancerIP: 168.10.0.21
  ports:
    - name: control-port
      protocol: TCP
      port: 9099
      targetPort: 9099
    - name: messaging-port
      protocol: TCP
      port: 9084
      targetPort: 9084
  type: LoadBalancer
```

Cheers Jochen
